baseURL = 'https://www.hazefest.ro/'
languageCode = 'en-us'
title = 'Haze Fest'
theme = "ananke"
[params]
  body_classes = "avenir white black"
  custom_css = ["custom.css"]
  text_color = "white"
  sectionPagesMenu = "main"
  google_fonts = [["Bebas Neue", "400"]]
  heading_font = "Bebas Neue"


[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/hazefestftw/"
label = "TND Facebook"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/hazefestromania/"
label = "TND Instagram"

[[menu.main]]